### ISSUE TITLE
Import into Prometheus

### ISSUE THREAD

**Issue by vegasbrianc** [infinityworksltd/docker-hub-exporter#2]
What are you using to import the metrics into Prometheus? I tried using the IP:Port as a target but it as not accepted. Do you recommend using the node exporter if so how do you configure it?

**Comment by Rucknar** [comment]
Hey @vegasbrianc Apologies for the tardy response, just seen this.
Prometheus is scraping this exporter, i'm using the associated Docker Hub image here:

https://hub.docker.com/r/infinityworks/docker-hub-exporter/
