### ISSUE TITLE
[Q] Did you reach Docker API call limit when scrape often?

### ISSUE THREAD

**Issue by zevarito** [infinityworksltd/docker-hub-exporter#3]
Hi,

I think Docker Webhooks for automated builds are really poor and found that this project exposing `docker_hub_image_last_updated` could be a good choice for image build notifications.

My concern is that I've seen in the past Docker rejecting API calls if those exceed some quantity by hour, I wonder how often are you getting metrics from Docker to avoid such a limitation.

How it works internally? Does have Docker-Hub-Exporter a polling interval different from the scrape interval by Prom? Does it occur sync/async ?

Thanks!

**Comment by Rucknar** [comment]
To be honest, i've not hit a limit yet. The documentations isn't really there but the response doesn't indicate any sort of rate limit.

Prometheus hits the /metrics page on the webserver, this then calls the 'Collector' class in script. Only actually does anything when the page is hit by the scrape.

**Comment by zevarito** [comment]
Thanks @Rucknar for clarifying!
