### ISSUE TITLE
[Feature Request] Login into private organizations

### ISSUE THREAD

**Issue by zevarito** [infinityworksltd/docker-hub-exporter#4]
Doesn't seems to have support for private organizations, if so, please tell me how to do it.
Thanks.

**Comment by Rucknar** [comment]
I'm not actually sure if it's possible. I suspect it is, though here are next to no docs. I'd have a good dig through google to see if it's possible/been done before. Happy to help implement support though!

**Comment by Rucknar** [comment]
Forgot to update this, should now work if you supply the auth token.
