### ISSUE TITLE
UnixHTTPConnectionPool when starting container

### ISSUE THREAD

**Issue by zevarito** [infinityworksltd/docker-hub-exporter#5]
When I try to create/start container `docker` the command fail with the following message but also breaks `docker`, the daemon even after restart is not able to bring up any single container. I have to remove the container manually from the fs to bring it up again. Does anyone have experienced this issue before?

```
Error starting container XXXXX UnixHTTPConnectionPool(host='localhost', port=None): Read timed out
```

**Comment by Rucknar** [comment]
Doesn't sound like anything the container could actually do! Do you have any issues running the container from the hub? If you paste in the command you used to build/run and the version of docker you are using, I'll try take a look.

**Comment by zevarito** [comment]
@Rucknar have to say that running pasting the exact command seems to work, docker doesn't present issues. I was creating/running the container with Ansible, never saw this issue before, I'll look to see what could be happening there, thanks for your help.

**Comment by Rucknar** [comment]
No worries, glad it's sorted @zevarito
