### ISSUE TITLE
What is the org name for offical images? 

### ISSUE THREAD

**Issue by megastef** [infinityworksltd/docker-hub-exporter#6]

**Comment by Rucknar** [comment]
'Infinityworks' hopefully should be in the readme doc

**Comment by megastef** [comment]
I would like to see downloads of and official image, e.g. https://hub.docker.com/_/solr/. But when I use _/solr  in images or just "solr", I don't get any metric. Could provide an example to monitor e.g. solr downloads?

**Comment by Rucknar** [comment]
Apologies, i miss-understood the original ticket. The exporter accesses the data through the API, for example: `https://hub.docker.com/v2/repositories/bob/bobcontainer/` I've just tried `https://hub.docker.com/v2/repositories/ubuntu/` to no avail. If you're aware of the API endpoints for the data, i'm happy to add in support to the script.

**Comment by megastef** [comment]
Solved: library/solr gets stats for solr
